name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-node-version: "20"

      - name: Build Frontend
        run: |
          npm install
          npm run build

      - name: Clear Old Files from Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_PASSWORD }}
          script: rm -rf /var/www/aadityapyarla/*

      - name: Deploy Static Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.SERVER_IP}}
          username: ubuntu
          key: ${{ secrets.SERVER_PASSWORD }}
          source: "dist/*"
          target: "/var/www/aadityapyarla"
          strip_components: 2
